@startuml
class MainForm <<partial>> {
    + MainForm()
    - InitializeComponent() : void
    - PaintBox_Paint(sender:object, e:PaintEventArgs) : void
    - MainForm_Resize(sender:object, e:EventArgs) : void
    - MainForm_Paint(sender:object, e:PaintEventArgs) : void
    - TrajectorySize_Scroll(sender:object, e:EventArgs) : void
    - TrajectorySpeed_Scroll(sender:object, e:EventArgs) : void
    - MovingPointTimer_Elapsed(sender:object, e:ElapsedEventArgs) : void
    - FigureSize_Scroll(sender:object, e:EventArgs) : void
    - FigureBreathSpeed_Scroll(sender:object, e:EventArgs) : void
    - ColorSwitchButton_Click(sender:object, e:EventArgs) : void
    - FigureSwitchButton_Click(sender:object, e:EventArgs) : void
    - MainForm_Load(sender:object, e:EventArgs) : void
    - MainForm_FormClosing(sender:object, e:FormClosingEventArgs) : void
}
MainForm o-> "Config" Config
MainForm o-> "_trajectory" Trajectory
MainForm o-> "MovingFigure" MovingFigureTrajectory

@enduml
